config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'users/sign_up' => 'devise/sessions#new'
  get 'homes/about' => 'homes#about', as: "about"
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


#                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#         post_images_new GET    /post_images/new(.:format)        post_images#new
#       post_images_index GET    /post_images/index(.:format)      post_images#index
#         post_images_show GET    /post_images/show(.:format)     post_images#show
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#                     root GET    /                               homes#top
#           users_sign_up GET    /users/sign_up(.:format)        devise/sessions#new
#                   about GET    /homes/about(.:format)          homes#about
# post_image_post_comments POST   /post_images/:post_image_id/post_comments(.:format)        post_comments#create
# post_image_post_comment DELETE /post_images/:post_image_id/post_comments/:id(.:format)    post_comments#destroy
#             post_images GET    /post_images(.:format)       post_images#index
#                         POST   /post_images(.:format)        post_images#create
#           new_post_image GET    /post_images/new(.:format)    post_images#new
#               post_image GET    /post_images/:id(.:format)    post_images#show
#                         DELETE /post_images/:id(.:format)    post_images#destroy
#               edit_user GET    /users/:id/edit(.:format)     users#edit
#                     user GET    /users/:id(.:format)          users#show
#                         PATCH  /users/:id(.:format)          users#update
#                         PUT    /users/:id(.:format)          users#update
# post_image_favorite DELETE /post_images/:post_image_id/favorite(.:format)        favorites#destroy
#                     POST   /post_images/:post_image_id/favorite(.:format)          favorites#create

app/models/post_image.rb
class PostImage < ApplicationRecord
    
    has_one_attached :image
    
    # 各モデルとの関連付け
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    # バリデーション
    # shop_nameが存在しているか
    validates :shop_name, presence: true
    #imageが存在しているか 
    validates :image, presence: true
    
    
    
    # プロフィール画像表示メソッド定義
    def get_image
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
        end
        image
    end
    
    def favorited_by?(user)
        # ユーザIDがいいねしたユーザIDのリストと一致するか
        favorites.exists?(user_id: user.id)
    end
    
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  # 投稿ページの表示
  def new
    @post_image = PostImage.new
  end
  
  # 投稿機能
  def create
    # モデルの枠に入力データ(ストロングパラメータ)が入っている
    @post_image = PostImage.new(post_image_params)
    # サインインしているユーザID＝投稿者Id
    @post_image.user_id = current_user.id
    
    # バリデーションチェック
    # 保存できなかったらnewを再表示
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end
  
  def index
    @post_images = PostImage.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end
  
  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_index_path
  end
  
  
  private
  
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
  
  
  
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_list.html.erb
<!--post_imagesは複数データなので一個ずつ取り出す-->
<% post_images.each do |post_image| %>
    <div>
        <%= link_to post_image_path(post_image.id) do %>
            <!--個々ののpost_imageにモデルに記述したget_imageのメソッドを適応-->
            <%= image_tag post_image.get_image %>
        <% end %>
        <!--PostImageモデルに紐づけられたUserモデル（post_image.user）のメソッド(.get_profile_image)-->
        <p>投稿ユーザー画像：<%= image_tag post_image.user.get_profile_image(100,100) %></p>
        
        <p>ショップ名：<%= post_image.shop_name %></p>
        <p>説明：<%= post_image.caption %></p>
        <!--アソシエーションを用いUserモデルのnameカラムから参照-->
        <p>ユーザネーム：<%= post_image.user.name %></p>
        <!--コメント件数-->
        <p><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %></p>
    </div>
<% end %>

<!--ページャ用-->
<%= paginate post_images %>

app/views/post_images/index.html.erb
<%= render 'list', post_images: @post_images %>
<!--部分テンプレート呼び出し、同フォルダなのでフォルダ名省略-->

app/views/post_images/new.html.erb
<!--エラー表示部分-->
<% if @post_image.errors.any? %>
    <%= @post_image.errors.count %>件のエラーが発生しました
    <ul>
        <% @post_image.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image do |f| %>
    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>
    <h4>ショップ名</h4>
    <%= f.text_field :shop_name %>
    <h4>説明</h4>
    <%= f.text_area :caption %>
    <%= f.submit '投稿' %>
<% end %>
    

app/views/post_images/show.html.erb
<!--画像詳細ページ-->
<div>
  <%= image_tag @post_image.get_image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  
  <!--PostImageモデルに紐づけられたUserモデル（post_image.user）のメソッド(.get_profile_image)-->
  <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
  
  <!--ここからいいね関係-->
  <% if @post_image.favorited_by?(current_user) %>
    <!--true=いいね済みの場合いいね解除-->
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %>いいね
      <% end %>
    </p>
  <% else %>
    <!--false=未いいねの場合いいね登録-->
    <p>
      <%= link_to post_image_favorite_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %>いいね
      <% end %>
    </p>
  <% end %>
</div>

<!--ここからコメント関係-->
<!--コメント一覧-->
<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <!--コメント一件づつ取り出して表示-->
  <!--PostImageモデルに結び付いたPostCommentモデルから取る-->
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <p><%= post_comment.user.name %></p>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %>
    <%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>
</div>

<!--コメント投稿機能-->
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>